name: Build branch

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Build branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - name: Set env
        run: |
          echo ::set-env name=GITHUB_SHA_SHORT::$(echo $GITHUB_SHA | head -c7)
          echo ::set-env name=DOCKER_IMAGE_URL::docker.pkg.github.com/pch/identt/identt

      - name: Docker Login
        env:
          DOCKER_REGISTRY_URL: docker.pkg.github.com
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: docker login $DOCKER_REGISTRY_URL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      # - name: Pull latest image to cache layers from
      #   run: docker pull $DOCKER_IMAGE_URL:latest

      - name: Build container image
        # run: docker build -t $DOCKER_IMAGE_URL:$GITHUB_SHA_SHORT -f $GITHUB_WORKSPACE/Dockerfile --build-arg -cache-from $DOCKER_IMAGE_URL:latest .
        run: docker build -t $DOCKER_IMAGE_URL:$GITHUB_SHA_SHORT -f $GITHUB_WORKSPACE/Dockerfile .

      - name: Update docker-compose-ci.yml vars
        run: |
          sed -i 's|<TAG>|'${GITHUB_SHA_SHORT}'|' $GITHUB_WORKSPACE/docker-compose-ci.yml

      - name: Run tests
        run: docker-compose -f $GITHUB_WORKSPACE/docker-compose-ci.yml up --exit-code-from rails

      - name: Tag image as latest
        run: docker tag $DOCKER_IMAGE_URL:$GITHUB_SHA_SHORT $DOCKER_IMAGE_URL:latest

      - name: Push image to registry
        run: docker push $DOCKER_IMAGE_URL
